/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJdbcPddDb4;

import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author aleole
 */
public class ControlFrame extends javax.swing.JFrame {

    /**
     * Creates new form ControlFrame
     */
    public ControlFrame(Connection outerConnection) {
        con = outerConnection;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ticketLabel = new javax.swing.JLabel();
        ticketComboBox = new javax.swing.JComboBox();
        questionLabel = new javax.swing.JLabel();
        questionComboBox = new javax.swing.JComboBox();
        questionContentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionContentTextArea = new javax.swing.JTextArea();
        questionPictureLabel = new javax.swing.JLabel();
        rewriteQuestionButton = new javax.swing.JButton();
        findQuestionButton = new javax.swing.JButton();
        isNotPicturedCheckBox = new javax.swing.JCheckBox();
        replacePictureButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        questionWrongAnswersTable = new javax.swing.JTable();
        questionRightAnswerLabel = new javax.swing.JLabel();
        questionRightAnswerTextField = new javax.swing.JTextField();
        addWrongAnswerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Управление");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Контроль результатов"));

        jTable1.setModel(buildTableModel(queryStud, rowsCountStud));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Корректирование вопросов"));

        ticketLabel.setText("Номер билета:");

        Object[] ticketNumbers = new Object[40];
        for(int i = 0; i < ticketNumbers.length; i++){
            ticketNumbers[i] = i +1;
        }
        ticketComboBox.setModel(new javax.swing.DefaultComboBoxModel(ticketNumbers));

        questionLabel.setText("Номер вопроса:");

        Object[] questionNumbers = new Object[20];
        for(int i = 0; i < questionNumbers.length; i++){
            questionNumbers[i] = i +1;
        }
        questionComboBox.setModel(new javax.swing.DefaultComboBoxModel(questionNumbers));

        questionContentLabel.setText("Вопрос:");

        questionContentTextArea.setColumns(20);
        questionContentTextArea.setRows(5);
        jScrollPane1.setViewportView(questionContentTextArea);

        questionPictureLabel.setText("Картинка для вопроса:");

        rewriteQuestionButton.setEnabled(false);
        rewriteQuestionButton.setText("Переписать вопрос");
        rewriteQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rewriteQuestionButtonActionPerformed(evt);
            }
        });

        findQuestionButton.setText("Найти вопрос");
        findQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findQuestionButtonActionPerformed(evt);
            }
        });

        isNotPicturedCheckBox.setText("Вопрос без изображения");

        replacePictureButton.setText("Заменить картинку");
        replacePictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacePictureButtonActionPerformed(evt);
            }
        });

        questionWrongAnswersTable.setModel(new javax.swing.table.DefaultTableModel(
            wrAnsOneQuest,
            columnNames
        ));
        questionWrongAnswersTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                questionWrongAnswersTableKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(questionWrongAnswersTable);

        questionRightAnswerLabel.setText("Правильный ответ:");

        addWrongAnswerButton.setText("Добавить неправильный ответ");
        addWrongAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWrongAnswerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ticketLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(questionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(findQuestionButton)
                .addGap(18, 18, 18)
                .addComponent(rewriteQuestionButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionContentLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(isNotPicturedCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(replacePictureButton))))
                    .addComponent(questionRightAnswerLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(questionRightAnswerTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addWrongAnswerButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketLabel)
                    .addComponent(ticketComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionLabel)
                    .addComponent(questionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findQuestionButton)
                    .addComponent(rewriteQuestionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionContentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionPictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isNotPicturedCheckBox)
                            .addComponent(replacePictureButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addWrongAnswerButton))
                .addGap(18, 18, 18)
                .addComponent(questionRightAnswerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionRightAnswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        sb.delete(0, sb.length());
        sb.append(queryStudRes);
        sb.append(jTable1.getValueAt(jTable1.getSelectedRow(), 3));
        sb.append("'");     
        JOptionPane.showMessageDialog(null, new JScrollPane(new JTable(buildTableModel(sb.toString(), rowsCountStudRes))));
    }//GEN-LAST:event_jTable1MouseClicked

    private void findQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findQuestionButtonActionPerformed
        try {
            // TODO add your handling code here:
            Dimension size = questionPictureLabel.getSize();
            questionId.delete(0, questionId.length());
            questionId.append('t');
            questionId.append(ticketComboBox.getSelectedItem());
            questionId.append('q');
            questionId.append(questionComboBox.getSelectedItem());
            questionPs = con.prepareStatement(queryQuestion);
            questionPs.setString(1, questionId.toString());
            ResultSet rs = questionPs.executeQuery();
            
            questWrAnsPs = con.prepareStatement(wrAnsQuery);
            questWrAnsPs.setString(1, questionId.toString());
            ResultSet wrAnsRs = questWrAnsPs.executeQuery();
            
            if(rs.next()){
                questionContentTextArea.setText(rs.getString("question_content"));
                questionRightAnswerTextField.setText(rs.getString("right_answer"));
                Image image = new ImageIcon(rs.getBytes("question_picture")).getImage();
                questionPictureLabel.setIcon(new ImageIcon(image.getScaledInstance(size.width, size.height, Image.SCALE_FAST)));
            }
            rs.close();
            
            columnNames = new Vector<Object>();
            ResultSetMetaData metaData = wrAnsRs.getMetaData();
            int columnCount = wrAnsRs.getMetaData().getColumnCount();
            for(int i = 1; i <= columnCount; i++){
                columnNames.add(metaData.getColumnName(i));
            }
            wrAnsOneQuest = new Vector<Vector<Object>>();
            while(wrAnsRs.next()){
                Vector<Object> vector = new Vector<Object>();
                for(int i = 1; i <= columnCount; i++){
                    vector.add(wrAnsRs.getObject(i));
                }
                wrAnsOneQuest.add(vector);
            }
            wrAnsRs.close();
            questionWrongAnswersTable.setModel(new DefaultTableModel(wrAnsOneQuest, columnNames));
            
            rewriteQuestionButton.setEnabled(true);
            
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_findQuestionButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            if(questionPs != null){
                questionPs.close();
            }
            if(questWrAnsPs != null){
                questWrAnsPs.close();
            }
            if(updateQuestionsPs != null){
                updateQuestionsPs.close();
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void replacePictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacePictureButtonActionPerformed
        // TODO add your handling code here:
        String fileName = null;
        String directory = null;
        if(!isNotPicturedCheckBox.isSelected()){
            FileDialog fd = new FileDialog(this, "Выберите картинку", FileDialog.LOAD);//!!!!!!!!?????????this?????????!!!!!!!!!!!
            fd.setDirectory("C:\\");
            fd.setFile("*.jpg");
            fd.setVisible(true);
           fileName = fd.getFile();
            directory = fd.getDirectory();
        }else{
            directory = "D:\\Projects\\different\\GuiJdbcPddDb4\\";
            fileName = "nonPictured.jpg";
        }
            if(fileName != null && directory != null){
                fullFileName = directory + fileName;
                imageForReplace = new ImageIcon(directory + fileName).getImage();
                Dimension size = questionPictureLabel.getSize();
                questionPictureLabel.setIcon(new ImageIcon(imageForReplace.getScaledInstance(size.width, size.height, Image.SCALE_FAST)));
            }
    }//GEN-LAST:event_replacePictureButtonActionPerformed

    private void rewriteQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rewriteQuestionButtonActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(
                null,
                "Вы уверены?",
                "Предупреждение",
                JOptionPane.YES_NO_CANCEL_OPTION);
        switch(dialogResult){
            case JOptionPane.YES_OPTION:
        {
            try {
                //обновим информацию в таблице questions
                if(fullFileName != null){
                    updateQuestionsPs = con.prepareStatement(updateQuestions);
                    File file = new File(fullFileName);
                    FileInputStream fis = new FileInputStream(file);
                    updateQuestionsPs.setBinaryStream(3, (InputStream)fis, (int)file.length());
                    updateQuestionsPs.setString(4, questionId.toString());
                    
                }else{
                    updateQuestionsPs = con.prepareStatement(updateQuestionsWithoutPicture);
                    
                    updateQuestionsPs.setString(3, questionId.toString());
                }
                updateQuestionsPs.setString(1, questionContentTextArea.getText().trim());
                updateQuestionsPs.setString(2, questionRightAnswerTextField.getText().trim());
                updateQuestionsPs.execute();
                //обновим информацию в таблице wrong_answers
                Statement st = con.createStatement();
                String deleteAllPriorWrongAnswers = "DELETE FROM Wrong_answers WHERE question_id='" + questionId.toString() + "'";
                st.execute(deleteAllPriorWrongAnswers);
                st.close();
                
                insertWrAnsPs = con.prepareStatement(insertSubsequentWrongAnswers);
                int rowCount = questionWrongAnswersTable.getModel().getRowCount();
                for(int i = 0; i < rowCount; i++){
                    insertWrAnsPs.setString(1, questionId.toString());
                    String str = (String)questionWrongAnswersTable.getModel().getValueAt(i, 0);
                    if(str != null && !str.equals("")){
                        insertWrAnsPs.setString(2, str);
                        insertWrAnsPs.execute();
                    }
                }
                JOptionPane.showMessageDialog(null, "Вопрос " + questionId.toString() + " изменён");
            } catch (SQLException | FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_rewriteQuestionButtonActionPerformed

    private void addWrongAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWrongAnswerButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)questionWrongAnswersTable.getModel();
        model.addRow(new Vector<Object>());
    }//GEN-LAST:event_addWrongAnswerButtonActionPerformed

    private void questionWrongAnswersTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_questionWrongAnswersTableKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            DefaultTableModel model = (DefaultTableModel)questionWrongAnswersTable.getModel();
            int selectedRow = questionWrongAnswersTable.getSelectedRow();
            if(selectedRow != -1){
                model.removeRow(selectedRow);
            }
        }
    }//GEN-LAST:event_questionWrongAnswersTableKeyPressed

    private DefaultTableModel buildTableModel(String query, String rowsCount){
        int count = 0;
        try {
            Statement st = con.createStatement();
            ResultSet countRs = st.executeQuery(rowsCount);
            if(countRs.next()){
                count = countRs.getInt(1);
            }
            countRs.close();
            ResultSet rs = st.executeQuery(query);
            ResultSetMetaData metaData = rs.getMetaData();
//--------------------------массив с именами столбцов---------------------------
            Object[] object = new Object[metaData.getColumnCount()];
            for(int i = 0; i < object.length; i++){
                object[i] = metaData.getColumnName(i + 1);
            }
//------------------------------------------------------------------------------
            //ArrayList<Object[]> arrayList = new ArrayList<Object[]>();
            Object[][] multiDimArray = new Object[count][metaData.getColumnCount()];
                for(int i = 0; i < multiDimArray.length; i++){
                    rs.next();
                    for(int j = 0; j < multiDimArray[i].length; j++){
                        multiDimArray[i][j] = rs.getString(j + 1);
                    }
                }
                st.close();
                return new DefaultTableModel(
                        multiDimArray,
                        object);
        } catch (SQLException ex) {
            System.out.println("Error: "+ ex.getMessage());
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ControlFrame().setVisible(true);
            }
        });
    }

    private Connection con;
    private String queryStudRes = "SELECT test_id, start_test_time, end_test_time, is_passed, quant_wr_ans FROM Passed_tests WHERE login='";
    private String rowsCountStudRes = "SELECT COUNT(*) FROM Passed_tests";
    private String queryStud = "SELECT last_name, first_name, group_id, login FROM examinees";
    private String rowsCountStud = "SELECT COUNT(*) FROM Examinees";
    private StringBuilder sb = new StringBuilder();
    private ArrayList<Answer> answers = new ArrayList<>();
    private PreparedStatement questionPs;
    private PreparedStatement questWrAnsPs;
    private PreparedStatement updateQuestionsPs;
    private PreparedStatement insertWrAnsPs;
    private String queryQuestion = "SELECT question_content, right_answer, question_picture FROM Questions WHERE question_id=?";
    private String wrAnsQuery = "SELECT wrong_answer FROM Wrong_answers WHERE question_id=?";
    private String updateQuestions = "UPDATE Questions SET"
            + " (question_content,"
            + " right_answer,"
            + " question_picture) = (?, ?, ?) WHERE question_id=?";
    private String updateQuestionsWithoutPicture = "UPDATE Questions SET"
            + " (question_content,"
            + " right_answer) = (?, ?) WHERE question_id=?";
    //private String deleteAllPriorWrongAnswers = "DELETE FROM Wrong_answers WHERE question_id=?";
    private String insertSubsequentWrongAnswers = "INSERT INTO Wrong_answers (question_id, wrong_answer) VALUES (?, ?)";
    private Vector<Object> columnNames;
    private Vector<Vector<Object>> wrAnsOneQuest;
    private StringBuilder questionId = new StringBuilder();
    private Image imageForReplace;
    private String fullFileName = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWrongAnswerButton;
    private javax.swing.JButton findQuestionButton;
    private javax.swing.JCheckBox isNotPicturedCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox questionComboBox;
    private javax.swing.JLabel questionContentLabel;
    private javax.swing.JTextArea questionContentTextArea;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel questionPictureLabel;
    private javax.swing.JLabel questionRightAnswerLabel;
    private javax.swing.JTextField questionRightAnswerTextField;
    private javax.swing.JTable questionWrongAnswersTable;
    private javax.swing.JButton replacePictureButton;
    private javax.swing.JButton rewriteQuestionButton;
    private javax.swing.JComboBox ticketComboBox;
    private javax.swing.JLabel ticketLabel;
    // End of variables declaration//GEN-END:variables
}
