/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJdbcPddDb4;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aleole
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent we){
                try {
                    if(drawFrame != null){
                        if(drawFrame.isVisible()){
                            drawFrame.completeTest();
                        }
                    }
                    if(con != null){
                        con.close();
                    }
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex.getMessage());
                    Logger.getLogger(StartFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        urlAddressJdbc = new UrlAddressJdbc();
        try {
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(urlAddressJdbc.getAddress(), urlAddressJdbc.getGuestLogin(), urlAddressJdbc.getGuestPassword());//устанавливаем соединение гостем
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
            problemsLabel.setText("Error: " + ex.getMessage());
            Logger.getLogger(DrawFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        noRegEnterButton = new javax.swing.JButton();
        controlButton = new javax.swing.JButton();
        problemsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Программа ПДД");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Авторизация"));

        loginLabel.setText("Логин:");

        passwordLabel.setText("Пароль:");

        enterButton.setText("Войти");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        noRegEnterButton.setText("Войти без регистрации");
        noRegEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRegEnterButtonActionPerformed(evt);
            }
        });

        controlButton.setText("Управление");
        controlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(problemsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noRegEnterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noRegEnterButton)
                    .addComponent(problemsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        privelegedConnect(false);
    }//GEN-LAST:event_enterButtonActionPerformed

    private void noRegEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRegEnterButtonActionPerformed
        // TODO add your handling code here:
        if(drawFrame != null){
                    drawFrame.dispose();
                }
        try{
            if(con != null){
                con.close();
        }
            con = DriverManager.getConnection(urlAddressJdbc.getAddress(), urlAddressJdbc.getGuestLogin(), urlAddressJdbc.getGuestPassword());//устанавливаем соединение гостем
        } catch (SQLException ex) {
                System.out.println("Error: " + ex.getMessage());
                Logger.getLogger(StartFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
                drawFrame = new DrawFrame(con, urlAddressJdbc.getGuestLogin(), false, false);
                drawFrame.setVisible(true);
    }//GEN-LAST:event_noRegEnterButtonActionPerformed

    private void controlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlButtonActionPerformed
        // TODO add your handling code here:
        privelegedConnect(true);

    }//GEN-LAST:event_controlButtonActionPerformed

    private void privelegedConnect(boolean isControl){
                try {
//------------------------------------------------------------------------------
                    isInstructor = false;
//------------------------------------------------------------------------------
//---------------------проверяем, что логин и пароль указаны--------------------
                    if(!loginTextField.getText().trim().equals("") && !passwordTextField.getText().trim().equals("")){
                        //---------------------проверяем наличие такого логина в системе----------------
                        if(con != null){
                            con.close();
                        }
                        con = DriverManager.getConnection(
                                urlAddressJdbc.getAddress(),
                                loginTextField.getText().trim(),
                                passwordTextField.getText().trim());
                                problemsLabel.setText("");
//--------------------------запрос к таблице examiners--------------------------
                        Statement st = con.createStatement();
                        StringBuilder sb = new StringBuilder();
                        sb.append("SELECT login FROM Examiners WHERE login='");
                        sb.append(loginTextField.getText().trim());
                        sb.append("'");
                        ResultSet rs = st.executeQuery(sb.toString());
                                    if(rs.next()){
                                        isInstructor = true;
                                    }
                                    st.close();
                                if(isControl){
                                    if(isInstructor){
                                        if(controlFrame != null){
                                        controlFrame.dispose();
                                        }
                                        controlFrame = new ControlFrame(con);
                                        controlFrame.setVisible(true);
                                    }else{
                                        problemsLabel.setText("Логин не найден в таблице инструкторов!");
                                    }
                                }else{
                                    if(drawFrame != null){
                                    drawFrame.dispose();
                                    }
                                drawFrame = new DrawFrame(
                                        con,
                                        loginTextField.getText().trim(),
                                        true,
                                        isInstructor);
                                drawFrame.setVisible(true);
                                }
                    }else{
                        System.out.println("Login or password not given!");
                        problemsLabel.setText("Логин или пароль не указаны!");
                    }                 
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex.getMessage());
                    problemsLabel.setText("Проверьте логин и пароль");
                    Logger.getLogger(StartFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    private Connection con = null;
    private UrlAddressJdbc urlAddressJdbc = null;
    private DrawFrame drawFrame = null;
    private ControlFrame controlFrame = null;
    private boolean isInstructor = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton controlButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JButton noRegEnterButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel problemsLabel;
    // End of variables declaration//GEN-END:variables
}
