/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import FanoCypher.FanoCoder;
import FanoCypher.Node;
import FanoCypher.Tree;
import FanoCypher.VisibleNode;
import cypher.CaesarCoder;
import cypher.TrithemiusCoder;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aleole
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        origMesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        origMesTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resMesTextArea = new javax.swing.JTextArea();
        resMesLabel = new javax.swing.JLabel();
        isShowProcCheckBox = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        trithemiusEncodeButton = new javax.swing.JButton();
        trithemiusDecodeButton = new javax.swing.JButton();
        trithemiusCodeWordLabel = new javax.swing.JLabel();
        codeWordTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        caesarEncodeButton = new javax.swing.JButton();
        caesarShiftLabel = new javax.swing.JLabel();
        caesarShiftComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        probabilityLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addRowButton = new javax.swing.JButton();
        delRowButton = new javax.swing.JButton();
        createTreeButton = new javax.swing.JButton();
        drawPanel = new FanoCypher.DrawPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cypher");

        origMesLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        origMesLabel.setText("Введите сообщение для кодирования:");

        origMesTextArea.setColumns(20);
        origMesTextArea.setRows(5);
        jScrollPane1.setViewportView(origMesTextArea);

        resMesTextArea.setColumns(20);
        resMesTextArea.setRows(5);
        jScrollPane2.setViewportView(resMesTextArea);

        resMesLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        resMesLabel.setText("Закодированное сообщение:");

        isShowProcCheckBox.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        isShowProcCheckBox.setText("Показать подробности");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ШИФРЫ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 14))); // NOI18N

        trithemiusEncodeButton.setText("Закодировать");
        trithemiusEncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trithemiusEncodeButtonActionPerformed(evt);
            }
        });

        trithemiusDecodeButton.setText("Раскодировать");
        trithemiusDecodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trithemiusDecodeButtonActionPerformed(evt);
            }
        });

        trithemiusCodeWordLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        trithemiusCodeWordLabel.setText("Кодовое слово:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(trithemiusEncodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trithemiusCodeWordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trithemiusDecodeButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trithemiusCodeWordLabel)
                        .addComponent(codeWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trithemiusEncodeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trithemiusDecodeButton)
                .addGap(0, 189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Шифр Тритемиуса", jPanel1);

        caesarEncodeButton.setText("Кодировать");
        caesarEncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caesarEncodeButtonActionPerformed(evt);
            }
        });

        caesarShiftLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        caesarShiftLabel.setText("Величина сдвига:");

        Object[] shifts = new Object[61];
        for(int i = 0; i < shifts.length; i++){
            shifts[i] = i - 30;
        }
        caesarShiftComboBox.setModel(new javax.swing.DefaultComboBoxModel(shifts));
        caesarShiftComboBox.setSelectedItem(0);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caesarEncodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(caesarShiftLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caesarShiftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caesarShiftLabel)
                    .addComponent(caesarShiftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caesarEncodeButton))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Шифр Цезаря", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Сообщение", "Вероятность"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        probabilityLabel.setText("Введите сообщения и их вероятности:");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addRowButton.setText("Добавить строку");
        addRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowButtonActionPerformed(evt);
            }
        });

        delRowButton.setText("Удалить строку");
        delRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRowButtonActionPerformed(evt);
            }
        });

        createTreeButton.setText("Построить дерево");
        createTreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTreeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createTreeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delRowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addRowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRowButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delRowButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createTreeButton)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        drawPanel.setBackground(new java.awt.Color(0, 0, 0));
        drawPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Кодовое дерево", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(probabilityLabel))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(probabilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Двоичный код Фано", jPanel3);

        jMenu1.setText("О программе");

        jMenuItem1.setText("Справка");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resMesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(isShowProcCheckBox))
                    .addComponent(origMesLabel)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(origMesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resMesLabel)
                    .addComponent(isShowProcCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trithemiusEncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trithemiusEncodeButtonActionPerformed
        // TODO add your handling code here:
        TrithemiusCoder trithemiusCoder = new TrithemiusCoder(
                isShowProcCheckBox.isSelected(),
                codeWordTextField.getText().trim(),
                origMesTextArea.getText().trim());
                trithemiusCoder.trithemiusEncodeMessage();
                resMesTextArea.setText(trithemiusCoder.presentMessage(" + "));
    }//GEN-LAST:event_trithemiusEncodeButtonActionPerformed

    private void trithemiusDecodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trithemiusDecodeButtonActionPerformed
        // TODO add your handling code here:
        TrithemiusCoder trithemiusCoder = new TrithemiusCoder(
        isShowProcCheckBox.isSelected(),
        codeWordTextField.getText().trim(),
        origMesTextArea.getText().trim());
        trithemiusCoder.trithemiusDecodeMessage();
        resMesTextArea.setText(trithemiusCoder.presentMessage(" - "));
    }//GEN-LAST:event_trithemiusDecodeButtonActionPerformed

    private void caesarEncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caesarEncodeButtonActionPerformed
        // TODO add your handling code here:
        CaesarCoder caesarCoder = new CaesarCoder(
                isShowProcCheckBox.isSelected(),
                (int)caesarShiftComboBox.getSelectedItem(),
                origMesTextArea.getText().trim());
        resMesTextArea.setText(caesarCoder.caesarСodeMessage());
    }//GEN-LAST:event_caesarEncodeButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,
                "Программа шифрует только строчные буквы кириллицы.\n"
                        + "Все остальные символы заменяет на пробел.");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void addRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRowButtonActionPerformed

    private void delRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delRowButtonActionPerformed

    private void createTreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTreeButtonActionPerformed
        // TODO add your handling code here:
        FanoCoder fanoCoder = new FanoCoder();
        Tree tree = new Tree(fanoCoder.getMessages());//построение дерева
//-------------------------показывание дерева-----------------------------------
        //построить список узлов, содержащий координаты
        ArrayList<VisibleNode> visibleNodes = new ArrayList<>();
        int tempX = drawPanel.getSize().width / 2;
        int tempY = 0;
        boolean isLeftBeforeRight = false;
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ArrayList<Integer> nodeIds = new ArrayList<>();//список для хранения узлов, у которых существует правый потомок
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        makeVisible(
                visibleNodes,
                nodeIds,
                tree.getRoot(),
                tree.getMaxlevel(),
                drawPanel.getSize().width / 10 * 6,
                drawPanel.getSize().height / 10 * 9,
                tempX,
                tempY,
                isLeftBeforeRight);
        drawPanel.setMaxLevel(tree.getMaxlevel());
        drawPanel.setVisibleNodes(visibleNodes);
        drawPanel.repaint();
    }//GEN-LAST:event_createTreeButtonActionPerformed

    private void makeVisible(
            ArrayList<VisibleNode> nodes,
            ArrayList<Integer> nodeIds,
            Node node,
            int maxLevel,
            int width,
            int height,
            int x,
            int y,
            boolean check){
        VisibleNode currentVisibleNode = new VisibleNode();
        y = y + height / (maxLevel + 1);
        currentVisibleNode.setX(x);
        currentVisibleNode.setY(y);
        techCounter++;
        //currentVisibleNode.setVisibleNodeMessage(Integer.toString(techCounter));
//------------------проверим сначала есть ли правый потомок---------------------
        if(node.getRightNode() != null){//добавим id в node и в список
            currentVisibleNode.id = techCounter;
            nodeIds.add(techCounter);
        }
//------------------------------------------------------------------------------
        if(node.isLeaf()){
            currentVisibleNode.setVisibleNodeMessage(node.getNodeMessage());
        }
        nodes.add(currentVisibleNode);
        if(node.getLeftNode() != null){
            x = x - width / ((int)Math.pow(2, node.getLevel() + 1) + 1);
            check = true;
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            nodes.get(nodes.size() - 1).leftLink = new Point(x, y + height / (maxLevel + 1));
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            makeVisible(nodes, nodeIds, node.getLeftNode(), maxLevel, width, height, x, y, check);
        }
        if(node.getRightNode() != null){
            if(check){
                x = x + (width / ((int)Math.pow(2, node.getLevel() + 1) + 1))*2;
            }else{
                x = x + width / ((int)Math.pow(2, node.getLevel() + 1) + 1);
            }
            check = false;
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            int index = nodeIds.size() - 1;
            int lastPrior = nodeIds.get(index);
            for(VisibleNode item : nodes){
                if(lastPrior == item.id){
                    item.rightLink = new Point(x, y + height / (maxLevel + 1));
                    nodeIds.remove(index);
                    break;
                }
            }
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            makeVisible(nodes, nodeIds, node.getRightNode(), maxLevel, width, height, x, y, check);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private int techCounter = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRowButton;
    private javax.swing.JButton caesarEncodeButton;
    private javax.swing.JComboBox caesarShiftComboBox;
    private javax.swing.JLabel caesarShiftLabel;
    private javax.swing.JTextField codeWordTextField;
    private javax.swing.JButton createTreeButton;
    private javax.swing.JButton delRowButton;
    private FanoCypher.DrawPanel drawPanel;
    private javax.swing.JCheckBox isShowProcCheckBox;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel origMesLabel;
    private javax.swing.JTextArea origMesTextArea;
    private javax.swing.JLabel probabilityLabel;
    private javax.swing.JLabel resMesLabel;
    private javax.swing.JTextArea resMesTextArea;
    private javax.swing.JLabel trithemiusCodeWordLabel;
    private javax.swing.JButton trithemiusDecodeButton;
    private javax.swing.JButton trithemiusEncodeButton;
    // End of variables declaration//GEN-END:variables
}
